name: Deploy Hosting (main)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Make env vars available at build time
      - name: Set env vars
        run: |
          echo "REACT_APP_RECAPTCHA_SITE_KEY=${{ secrets.REACT_APP_RECAPTCHA_SITE_KEY }}" >> $GITHUB_ENV
          echo "REACT_APP_RECAPTCHA_VERIFY_URL=${{ secrets.RECAPTCHA_VERIFY_URL || secrets.REACT_APP_RECAPTCHA_VERIFY_URL }}" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & build
        run: |
          npm ci
          npm run build

      # Deploy Hosting only
      - name: Deploy Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MISHMAR_7600C }}
          channelId: live
          projectId: mishmar-7600c